const indiaAdjacency = {
  "Jammu & Kashmir": ["Himachal Pradesh", "Punjab", "Ladakh"],
  "Ladakh": ["Jammu & Kashmir", "Himachal Pradesh"],
  "Himachal Pradesh": ["Jammu & Kashmir", "Ladakh", "Punjab", "Haryana", "Uttarakhand", "Uttar Pradesh"],
  "Punjab": ["Jammu & Kashmir", "Himachal Pradesh", "Haryana", "Rajasthan"],
  "Haryana": ["Punjab", "Himachal Pradesh", "Uttarakhand", "Uttar Pradesh", "Rajasthan", "Delhi"],
  "Delhi": ["Haryana", "Uttar Pradesh", "Rajasthan"],
  "Uttarakhand": ["Himachal Pradesh", "Haryana", "Uttar Pradesh"],
  "Uttar Pradesh": ["Uttarakhand", "Himachal Pradesh", "Haryana", "Delhi", "Rajasthan", "Madhya Pradesh", "Chhattisgarh", "Jharkhand", "Bihar", "Nepal"],
  "Rajasthan": ["Punjab", "Haryana", "Delhi", "Uttar Pradesh", "Madhya Pradesh", "Gujarat"],
  "Bihar": ["Uttar Pradesh", "Jharkhand", "West Bengal", "Nepal"],
  "Jharkhand": ["Bihar", "Uttar Pradesh", "Chhattisgarh", "Odisha", "West Bengal"],
  "West Bengal": ["Bihar", "Jharkhand", "Odisha", "Sikkim", "Assam", "Bangladesh"],
  "Sikkim": ["West Bengal", "Assam"],
  "Assam": ["Sikkim", "West Bengal", "Meghalaya", "Tripura", "Mizoram", "Manipur", "Nagaland", "Arunachal Pradesh"],
  "Arunachal Pradesh": ["Assam", "Nagaland"],
  "Nagaland": ["Arunachal Pradesh", "Assam", "Manipur"],
  "Manipur": ["Nagaland", "Assam", "Mizoram"],
  "Mizoram": ["Manipur", "Assam", "Tripura"],
  "Tripura": ["Mizoram", "Assam"],
  "Meghalaya": ["Assam"],
  "Odisha": ["Jharkhand", "West Bengal", "Chhattisgarh", "Andhra Pradesh"],
  "Chhattisgarh": ["Uttar Pradesh", "Jharkhand", "Odisha", "Andhra Pradesh", "Telangana", "Maharashtra", "Madhya Pradesh"],
  "Madhya Pradesh": ["Rajasthan", "Uttar Pradesh", "Chhattisgarh", "Maharashtra", "Gujarat"],
  "Gujarat": ["Rajasthan", "Madhya Pradesh", "Maharashtra"],
  "Maharashtra": ["Gujarat", "Madhya Pradesh", "Chhattisgarh", "Telangana", "Andhra Pradesh", "Karnataka", "Goa"],
  "Goa": ["Maharashtra", "Karnataka"],
  "Karnataka": ["Goa", "Maharashtra", "Telangana", "Andhra Pradesh", "Tamil Nadu", "Kerala"],
  "Telangana": ["Maharashtra", "Chhattisgarh", "Odisha", "Andhra Pradesh", "Karnataka"],
  "Andhra Pradesh": ["Telangana", "Odisha", "Chhattisgarh", "Maharashtra", "Karnataka", "Tamil Nadu"],
  "Tamil Nadu": ["Karnataka", "Andhra Pradesh", "Kerala"],
  "Kerala": ["Karnataka", "Tamil Nadu"],
};

export default indiaAdjacency;